### ISSUE TITLE
assignment destination is read-only for numpy array 

### ISSUE THREAD

**Issue by leoyala** [NeuroJSON/pyjdata#4]
Hi,

I have noticed that after migrating from `jdata==0.3.7` to `jdata==0.5.1` I am getting the error `ValueError: assignment destination is read-only` after trying to modify the values that I load with `jdata.load`. Is this behaviour intended or is there something happening that we are unaware of?

**Comment by fangq** [comment]
@leoyala, thanks for reporting this. is there a small data file that I can reproduce this error?

**Comment by leoyala** [comment]
HI @fangq,

Here is an exemplary file, I had to compress it because GitHub does not support `.jnii` files apparently.
[MyVolumeName_471_output.zip](https://github.com/NeuroJSON/pyjdata/files/10077366/MyVolumeName_471_output.zip)

**Comment by fangq** [comment]
@leoyala, I tried it on my Ubuntu 18.04 box, it seems to work ok, can you let me know your python/numpy version? I can find a machine with similar condition and test again.
```
fangq@taote$ python3
Python 3.6.9 (default, Jun 29 2022, 11:45:57) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jdata as jd
>>> a=jd.load('MyVolumeName_471_output.jnii');
>>> a
{'NIFTIHeader': {'NIIHeaderSize': 348, 'Dim': [120, 60, 121], 'Param1': 0, 'Param2': 0, 'Param3': 0, 'Intent': 0, 'DataType': 'single', 'BitDepth': 32, 'FirstSliceID': 0, 'VoxelSize': [0.5, 0.5, 0.5], 'Orientation': {'x': 'r', 'y': 'a', 'z': 's'}, 'ScaleSlope': 1, 
    ...
      dtype=float32)}
>>> import numpy as np
>>> np.__version__
'1.19.3'
>>> jd.__version__
'0.5.1'
```

**Comment by leoyala** [comment]
@fangq I am using `numpy==1.21.4` in python 3.8.8 and Ubuntu 20.04. The problem does not appear when loading the data, but when I try to modify some of the `numpy` arrays in the loaded data. For example, assigning some of the values of the array in `'NIFTIData'` to `0`.

**Comment by fangq** [comment]
@leoyala, the mentioned issue has been fixed. I also updated jdata on pypi to 0.5.2 to include this fix.

I initially removed `bytearray()` with an attempt of accelerating the loading speed, but it appears that `frombuffer` alone returns a read-only view.

I tested and it should work now. feel free to reopen if you see any additional issue.
